name: BIGE
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - cudatoolkit
  - imageio
  - ipykernel
  - jupyter
  - matplotlib
  - notebook
  - pandas
  - pip
  - python=3.10
  - scikit-learn
  - scipy
  - tensorboard
  - pip:
    - deepspeed
    - git+https://github.com/nghorbani/human_body_prior
    - git+https://github.com/openai/CLIP.git
    - nimblephysics